# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KKEHAdH78--EH_xdFjKn78uOUN89z_aA
"""

import matplotlib.pyplot as plt
import numpy as np

#error metric
def error_metric(y, y_hat, c):
    import numpy as np
    err = y-y_hat
    err = (1-c)*err**2 + c*np.maximum(0,err)**2
    return np.sum(err)/err.shape[0]

#clean the dataset
def clean_train_data(train):
    cols_with_missing = [col for col in train.columns if train[col].isna().sum() > 0 and col != "SurvivalTime"]
    train_clean = train.drop(columns=cols_with_missing)
    train_clean = train_clean.dropna(subset=["SurvivalTime"])
    train_clean = train_clean[train_clean["Censored"] == 0]
    return train_clean

#plot y vs yhat
def plot_y_yhat(y, yhat):
    y = np.array(y)
    yhat = np.array(yhat)

    plt.figure(figsize=(6,6))
    plt.scatter(y, yhat, alpha=0.6)
    plt.xlabel("True y")
    plt.ylabel("Predicted y")
    plt.title("y vs yhat")

    # Draw y=x line
    x_min, x_max = np.min(y), np.max(y)
    plt.plot([x_min, x_max], [x_min, x_max], color='red')

    plt.axis('square')
    plt.show()

# Polynomial Regression
# best_model_fitted, best_degree, cv_scores

def select_polynomial_model(
    X_tr, y_tr,
    degrees=[1, 2, 3, 4, 5],
    n_splits=5,
    shuffle=True
):

    cv_scores = {}
    best_score = np.inf
    best_degree = None
    best_model = None

    for d in degrees:
        # Pipeline: standardizzazione -> espansione polinomiale -> regressione lineare
        pipe_poly = Pipeline([
            ("scaler", StandardScaler()),
            ("poly", PolynomialFeatures(degree=d, include_bias=False)),
            ("lin", LinearRegression())
        ])

        kfold = KFold(n_splits=n_splits, shuffle=shuffle)

        # out-of-fold predictions sul training
        y_tr_oof = cross_val_predict(pipe_poly, X_tr, y_tr, cv=kfold)

        # tua metrica (es. MSE)
        cmse_cv = error_metric(y_tr, y_tr_oof,c=0)
        cv_scores[d] = cmse_cv

        # tiene traccia del modello migliore
        if cmse_cv < best_score:
            best_score = cmse_cv
            best_degree = d
            # rifitta sul training completo
            best_model = pipe_poly.fit(X_tr, y_tr)

    return best_model, best_degree, cv_scores

# k-Nearest Neighbors
#best_model_fitted, best_params, cv_scores
def select_knn_model(
    X_tr, y_tr,
    k_list=[3, 5, 7, 9, 11],
    weights_list=["uniform", "distance"],
    n_splits=5,
    shuffle=True
):

    cv_scores = {}
    best_score = np.inf
    best_params = None
    best_model = None

    for k in k_list:
        for w in weights_list:
            pipe_knn = Pipeline([
                ("scaler", StandardScaler()),
                ("knn", KNeighborsRegressor(
                    n_neighbors=k,
                    weights=w
                ))
            ])

            kfold = KFold(n_splits=n_splits, shuffle=shuffle)

            # out-of-fold predictions sul training
            y_tr_oof = cross_val_predict(pipe_knn, X_tr, y_tr, cv=kfold)

            cmse_cv = error_metric(y_tr, y_tr_oof,c=0)
            cv_scores[(k, w)] = cmse_cv

            if cmse_cv < best_score:
                best_score = cmse_cv
                best_params = {"k": k, "weights": w}
                best_model = pipe_knn.fit(X_tr, y_tr)

    return best_model, best_params, cv_scores

#plot y vs yhat
def plot_y_vs_yhat(y_true, y_pred, title="y vs y_hat"):
    plt.figure(figsize=(6, 6))
    plt.scatter(y_true, y_pred, alpha=0.6)

    # Diagonale perfetta y = y_hat
    min_val = min(np.min(y_true), np.min(y_pred))
    max_val = max(np.max(y_true), np.max(y_pred))
    plt.plot([min_val, max_val], [min_val, max_val], linestyle="--")

    plt.xlabel("True y")
    plt.ylabel("Predicted y")
    plt.title(title)
    plt.grid(True)
    plt.tight_layout()
    plt.show()

def evaluate_model_cv(model, X, y, n_splits=5, shuffle=True):

    kf = KFold(n_splits=n_splits, shuffle=shuffle)
    fold_errors = []

    for train_idx, test_idx in kf.split(X):
        X_tr, X_te = X.iloc[train_idx], X.iloc[test_idx]
        y_tr, y_te = y.iloc[train_idx], y.iloc[test_idx]

        m = clone(model)
        m.fit(X_tr, y_tr)

        y_hat = m.predict(X_te)
        err = error_metric(y_te.values, y_hat, c=0)
        fold_errors.append(err)

    return fold_errors